@extends('layouts.app', ['role' => 'admin'])
@section('title', 'Métricas e IA')
@section('content')
<x-page-header eyebrow="Observabilidade" title="Métricas e inteligência artificial" description="Uso, custo e qualidade operacional das correções assistidas."><button class="btn btn-light" data-demo-action><i class="bi bi-calendar3 me-1"></i> 01–20 de agosto</button></x-page-header>
<div class="stats-grid"><x-stat-card label="Requisições à IA" value="486" icon="bi-stars" /><x-stat-card label="Latência média" value="11,4 s" icon="bi-stopwatch" tone="blue" /><x-stat-card label="Taxa de sucesso" value="98,7%" icon="bi-check2-circle" tone="green" /><x-stat-card label="Falhas no período" value="6" icon="bi-exclamation-triangle" tone="orange" :trend-up="false" /></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-header"><div><h2>Consumo diário</h2><p>Quantidade de correções e custo estimado</p></div></div><div class="panel-body pb-5"><div class="chart-placeholder"><span class="chart-column" data-label="14/08" style="height:45%"></span><span class="chart-column" data-label="15/08" style="height:80%"></span><span class="chart-column" data-label="16/08" style="height:28%"></span><span class="chart-column" data-label="17/08" style="height:20%"></span><span class="chart-column" data-label="18/08" style="height:61%"></span><span class="chart-column" data-label="19/08" style="height:100%"></span><span class="chart-column" data-label="Hoje" style="height:72%"></span></div></div></section>
<section class="panel"><div class="panel-header"><div><h2>Limites de segurança</h2><p>Consumo do orçamento configurado</p></div></div><div class="panel-body"><div class="metric-bar"><div class="metric-bar-label"><span>Orçamento mensal</span><span>R$ 42,18 / R$ 150</span></div><div class="progress"><div class="progress-bar" style="width:28%"></div></div></div><div class="metric-bar"><div class="metric-bar-label"><span>Requisições por minuto</span><span>4 / 30</span></div><div class="progress"><div class="progress-bar bg-success" style="width:13%"></div></div></div><div class="metric-bar"><div class="metric-bar-label"><span>Fila atual</span><span>3 / 100 jobs</span></div><div class="progress"><div class="progress-bar bg-info" style="width:3%"></div></div></div><div class="callout callout-info mt-4"><i class="bi bi-shield-check"></i><span>Nenhum limite foi ultrapassado. Alertas serão enviados com 70%, 90% e 100% do orçamento.</span></div></div></section></div>
<section class="panel mt-4"><div class="panel-header"><div><h2>Falhas recentes</h2><p>Eventos que exigiram nova tentativa</p></div></div><div class="table-responsive"><table class="table formai-table"><thead><tr><th>Job</th><th>Prova</th><th>Motivo</th><th>Tentativas</th><th>Status</th></tr></thead><tbody><tr><td>#AI-1098</td><td>Interpretação de texto</td><td>Tempo limite do provedor</td><td>2 de 3</td><td><x-status-badge status="Processando IA" /></td></tr><tr><td>#AI-1084</td><td>Brasil República</td><td>Resposta fora do formato</td><td>3 de 3</td><td><x-status-badge status="Falha na IA" /></td></tr></tbody></table></div></section>
@endsection
