@extends('layouts.app', ['role' => 'teacher'])
@section('title', 'Revisar correção')
@section('content')
<x-page-header eyebrow="Tentativa #FA-{{ $attemptId }}" title="Revisar correção" description="Ana Beatriz · Interpretação de texto · entregue hoje às 09:57"><a class="btn btn-light" href="{{ route('demo.teacher.gradings') }}"><i class="bi bi-arrow-left me-1"></i> Voltar</a><button class="btn btn-primary" data-demo-action>Salvar e publicar nota</button></x-page-header>
<div class="callout callout-warning mb-4"><i class="bi bi-person-check"></i><span><strong>A decisão é sua.</strong> A IA apresenta apenas uma sugestão. Confira a resposta, os critérios e a justificativa antes de publicar.</span></div>
<div class="dashboard-grid">
    <div><section class="panel"><div class="panel-header"><div><h2>Questão 3 de 4</h2><p>Questão dissertativa · valor: 4,0 pontos</p></div><span class="question-meta">Versão da prova: 1</span></div><div class="panel-body"><p class="question-text">A partir do texto apresentado, explique como o autor constrói sua tese e cite dois recursos argumentativos utilizados.</p><label class="form-label mt-2">Resposta do aluno</label><div class="question-answer">O autor constrói a tese apresentando inicialmente o problema e depois utiliza exemplos do cotidiano para aproximar o leitor. Ele também usa dados estatísticos para reforçar a credibilidade e uma comparação entre duas situações para mostrar as consequências do problema.</div><div class="d-flex gap-3 mt-3 question-meta"><span><i class="bi bi-fonts me-1"></i>43 palavras</span><span><i class="bi bi-clock me-1"></i>Respondida em 8 min</span><span><i class="bi bi-clipboard-check me-1"></i>Sem similaridade relevante</span></div></div></section>
    <section class="panel mt-4"><div class="panel-header"><div><h2>Critérios da rubrica</h2><p>Ajuste a pontuação caso discorde da sugestão</p></div></div><div class="table-responsive"><table class="table formai-table"><thead><tr><th>Critério</th><th>Justificativa da IA</th><th style="width:130px">Pontuação</th></tr></thead><tbody><tr><td><b>Compreensão da tese</b><span class="table-subtitle">Máximo: 1,5</span></td><td>Identificou corretamente a progressão utilizada pelo autor.</td><td><input class="form-control form-control-sm" value="1,4 / 1,5"></td></tr><tr><td><b>Recursos argumentativos</b><span class="table-subtitle">Máximo: 2,0</span></td><td>Apresentou dois recursos e explicou sua função no texto.</td><td><input class="form-control form-control-sm" value="1,8 / 2,0"></td></tr><tr><td><b>Clareza e coesão</b><span class="table-subtitle">Máximo: 0,5</span></td><td>Resposta clara, objetiva e bem conectada.</td><td><input class="form-control form-control-sm" value="0,5 / 0,5"></td></tr></tbody></table></div></section></div>
    <aside><section class="ai-box"><div class="panel-header"><div><h2 class="ai-title"><i class="bi bi-stars"></i>Sugestão da IA</h2><p>Modelo externo · processada em 9,8 s</p></div></div><div class="panel-body"><div class="score-ring">3,7</div><div class="text-center question-meta mb-4">de 4,0 pontos · confiança alta (91%)</div><label class="form-label">Feedback sugerido ao aluno</label><textarea class="form-control" rows="7">Sua resposta identifica corretamente como a tese é construída e apresenta dois recursos argumentativos relevantes. Para ficar ainda mais completa, você poderia relacionar de modo mais explícito os dados estatísticos à credibilidade do argumento.</textarea><div class="callout callout-info mt-3"><i class="bi bi-info-circle"></i><span>Nenhum sinal de resposta fora do tema foi identificado.</span></div></div></section>
    <section class="panel mt-4"><div class="panel-header"><div><h2>Nota da questão</h2><p>Valor final definido pelo professor</p></div></div><div class="panel-body"><div class="input-group"><input class="form-control form-control-lg fw-bold" value="3,7"><span class="input-group-text">/ 4,0</span></div><label class="form-label mt-3">Observação interna</label><textarea class="form-control" rows="3" placeholder="Opcional; não será exibida ao aluno"></textarea></div></section></aside>
</div>
@endsection
