@extends('layouts.app', ['role' => 'teacher'])
@section('title', 'Criar prova')
@section('content')
<x-page-header eyebrow="Nova avaliação" title="Criar prova" description="Configure a prova, adicione questões e revise antes de publicar."><button class="btn btn-light" data-demo-action>Salvar rascunho</button><button class="btn btn-primary" data-demo-action>Revisar e publicar</button></x-page-header>
<div class="stepper"><div class="step active"><span>1</span>Informações</div><div class="step active"><span>2</span>Questões</div><div class="step"><span>3</span>Configurações</div><div class="step"><span>4</span>Revisão</div></div>
<div class="dashboard-grid">
    <div>
        <section class="panel mb-4"><div class="panel-header"><div><h2>Informações da prova</h2><p>Identificação e público da avaliação</p></div></div><div class="panel-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Título</label><input class="form-control" value="Revolução Industrial"></div><div class="col-md-4"><label class="form-label">Turma</label><select class="form-select"><option>História · 2º A</option><option>História · 2º B</option></select></div><div class="col-md-6"><label class="form-label">Início</label><input class="form-control" type="datetime-local" value="2026-08-22T14:00"></div><div class="col-md-6"><label class="form-label">Encerramento</label><input class="form-control" type="datetime-local" value="2026-08-22T15:30"></div><div class="col-12"><label class="form-label">Orientações aos alunos</label><textarea class="form-control" rows="3">Leia atentamente cada questão e desenvolva suas respostas com clareza.</textarea></div></div></div></section>
        <section class="panel"><div class="panel-header"><div><h2>Questões <span class="text-secondary fw-normal">(3)</span></h2><p>Arraste para reorganizar a ordem</p></div><div class="d-flex gap-2"><button class="btn btn-sm btn-light" data-demo-action><i class="bi bi-collection me-1"></i> Banco de questões</button><button class="btn btn-sm btn-primary" data-demo-action><i class="bi bi-plus-lg me-1"></i> Criar questão</button></div></div><div class="panel-body">
            <article class="question-card"><div class="question-head"><i class="bi bi-grip-vertical text-secondary"></i><span class="question-number">1</span><x-status-badge status="Alternativa única" /><span class="question-meta ms-auto">2,0 pontos</span></div><p class="question-text">Em qual país teve início a Revolução Industrial?</p><div class="row g-2"><div class="col-sm-6"><div class="answer-option"><input type="radio" checked disabled>Inglaterra</div></div><div class="col-sm-6"><div class="answer-option"><input type="radio" disabled>França</div></div><div class="col-sm-6"><div class="answer-option"><input type="radio" disabled>Alemanha</div></div><div class="col-sm-6"><div class="answer-option"><input type="radio" disabled>Estados Unidos</div></div></div></article>
            <article class="question-card"><div class="question-head"><i class="bi bi-grip-vertical text-secondary"></i><span class="question-number">2</span><x-status-badge status="Dissertativa" /><span class="question-meta ms-auto">5,0 pontos</span></div><p class="question-text">Explique duas consequências sociais da Revolução Industrial.</p><div class="question-answer text-secondary">Resposta longa do aluno · Correção assistida por IA com rubrica</div></article>
            <article class="question-card"><div class="question-head"><i class="bi bi-grip-vertical text-secondary"></i><span class="question-number">3</span><x-status-badge status="Verdadeiro ou falso" /><span class="question-meta ms-auto">3,0 pontos</span></div><p class="question-text">A máquina a vapor contribuiu para a mecanização da produção.</p></article>
        </div></section>
    </div>
    <aside>
        <section class="panel mb-4"><div class="panel-header"><div><h2>Configuração rápida</h2><p>Comportamento durante a prova</p></div></div><div class="panel-body"><label class="form-label">Duração</label><div class="input-group mb-3"><input class="form-control" type="number" value="90"><span class="input-group-text">minutos</span></div><div class="form-check form-switch mb-3"><input class="form-check-input" id="shuffleQuestions" type="checkbox" checked><label class="form-check-label small" for="shuffleQuestions">Embaralhar questões</label></div><div class="form-check form-switch mb-3"><input class="form-check-input" id="shuffleOptions" type="checkbox" checked><label class="form-check-label small" for="shuffleOptions">Embaralhar alternativas</label></div><div class="form-check form-switch mb-3"><input class="form-check-input" id="tabTracking" type="checkbox" checked><label class="form-check-label small" for="tabTracking">Registrar saída da aba</label></div><div class="form-check form-switch"><input class="form-check-input" id="copyBlock" type="checkbox"><label class="form-check-label small" for="copyBlock">Desencorajar copiar e colar</label></div></div></section>
        <section class="ai-box"><div class="panel-header"><div><h2 class="ai-title"><i class="bi bi-stars"></i>Contexto para a IA</h2><p>Usado apenas nas questões dissertativas</p></div></div><div class="panel-body"><label class="form-label">PDF de referência</label><div class="question-answer mb-3"><i class="bi bi-file-earmark-pdf text-danger me-2"></i>revolucao-industrial.pdf <small class="text-secondary">· 2,4 MB</small></div><label class="form-label">Orientações complementares</label><textarea class="form-control" rows="5">Considere a relação entre urbanização, condições de trabalho e formação da classe operária.</textarea><div class="form-text mt-2"><i class="bi bi-shield-check me-1"></i>A nota continuará dependendo da sua revisão.</div></div></section>
    </aside>
</div>
@endsection
